### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/SchemeEditor#16]
Yep, need to do it.

**Comment by mildlydiverting** [comment]
See https://github.com/facelessuser/ColorSchemeEditor/pull/17

**Comment by facelessuser** [comment]
This is going to get updated with the new version. The tool itself will be pip installable.  It should support the latest ST3 tmTheme files (popupCss, phantomCss, x11 named colors, etc.).  Just need to update readme.
